### ISSUE TITLE
Questions about the application

### ISSUE THREAD

**Issue by CapLeviCorps** [Yoyolick/OpenAnimeList#1]
What Trackers would this App contain? Also could you share some screenshots if possible?

**Comment by Yoyolick** [comment]
Do you think you could elaborate on trackers? If you mean automatic show tracking that's something I'm still looking into, I'm not sure how possible it is due to there being no apis for anime streaming services that i know of. Below is an image of how the application looks now, I'm not sure how the design will change as its WIP as of right now.

![image](https://user-images.githubusercontent.com/43967290/103568296-50577500-4e93-11eb-8ab6-ff7b111632b5.png)

Just to explain the UI I'm going for, the three tabs at the top are the categories you can place anime into based on watch status, on the left panel you will see every anime you have put into the category you have selected at the top, and on the right panel you can see details about the anime you clicked on in the left panel (like the cover photo and the synopsis)

**Comment by CapLeviCorps** [comment]
By Trackers I mean MAL/Anilist/Kitsu etc.

**Comment by Yoyolick** [comment]
At the moment I'm planning on hosting the database myself and not trying to pull from other trackers, but for the right sidebar where it pulls up metadata about the anime I will most likely be pulling that from the myanimelist page
